/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodosImport } from './routes/todos'
import { Route as PostsImport } from './routes/posts'
import { Route as AboutImport } from './routes/about'
import { Route as TodosTodoIdImport } from './routes/todos.$todoId'

// Create/Update Routes

const TodosRoute = TodosImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRoute,
} as any)

const PostsRoute = PostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const TodosTodoIdRoute = TodosTodoIdImport.update({
  id: '/$todoId',
  path: '/$todoId',
  getParentRoute: () => TodosRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosImport
      parentRoute: typeof rootRoute
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdImport
      parentRoute: typeof TodosImport
    }
  }
}

// Create and export the route tree

interface TodosRouteChildren {
  TodosTodoIdRoute: typeof TodosTodoIdRoute
}

const TodosRouteChildren: TodosRouteChildren = {
  TodosTodoIdRoute: TodosTodoIdRoute,
}

const TodosRouteWithChildren = TodosRoute._addFileChildren(TodosRouteChildren)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/todos': typeof TodosRouteWithChildren
  '/todos/$todoId': typeof TodosTodoIdRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/todos': typeof TodosRouteWithChildren
  '/todos/$todoId': typeof TodosTodoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRoute
  '/todos': typeof TodosRouteWithChildren
  '/todos/$todoId': typeof TodosTodoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/posts' | '/todos' | '/todos/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/posts' | '/todos' | '/todos/$todoId'
  id: '__root__' | '/about' | '/posts' | '/todos' | '/todos/$todoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  PostsRoute: typeof PostsRoute
  TodosRoute: typeof TodosRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  PostsRoute: PostsRoute,
  TodosRoute: TodosRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/posts",
        "/todos"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/posts": {
      "filePath": "posts.tsx"
    },
    "/todos": {
      "filePath": "todos.tsx",
      "children": [
        "/todos/$todoId"
      ]
    },
    "/todos/$todoId": {
      "filePath": "todos.$todoId.tsx",
      "parent": "/todos"
    }
  }
}
ROUTE_MANIFEST_END */
